sudo: false
language: node_js
node_js:
  - "10.14.1"
notifications:
  disabled: true

# Setup Postgres database for testing
services:
  - postgresql
script:
  - sequelize db:create --env test
  - sequelize db:migrate --env test