openapi: "3.0.1"
info:
  title: Github for Jira Gateway
  description: It routes things
  version: "0.0.1"

paths:
  /$default:
    x-amazon-apigateway-any-method:
      isDefaultRoute: true
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        requestParameters:
          integration.request.header.Host: "'{{ServerHost}}'"
        uri: "https://{{ServerHost}}"
        connectionType: "INTERNET"

  /version:
    get:
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "https://{{ServerHost}}/version"
        connectionType: "INTERNET"

#  /{proxy+}:
#    x-amazon-apigateway-any-method:
#      x-amazon-apigateway-integration:
#        payloadFormatVersion: "1.0"
#        type: "http_proxy"
#        httpMethod: "ANY"
#        requestParameters:
#          integration.request.header.Host: "'{{ServerHost}}'"
#        uri: "https://{{ServerHost}}/{proxy}"
#        connectionType: "INTERNET"

  /healthcheck:
    get:
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: "{\"status\": \"ok\"}"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"

  /github/webhooks:
    post:
      responses:
        '200':
          description: "Default response for POST /github/webhooks"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "POST"
        credentials: "{{RoleARN}}"
        uri: "{{GithubQueueUrl}}?Action=SendMessage&MessageBody=$input.body"
        requestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
        passthroughBehavior: "never"
        connectionType: "INTERNET"

  /jira/events:
    post:
      responses:
        '200':
          description: "Default response for POST /github/webhooks"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "POST"
        credentials: "{{RoleARN}}"
        uri: "{{JiraQueueUrl}}?Action=SendMessage&MessageBody=$input.body"
        requestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
        passthroughBehavior: "never"
        connectionType: "INTERNET"
#        integrationSubtype: "SQS-SendMessage"
#        credentials: "{{RoleARN}}"
#        requestParameters:
#          MessageBody: "$request.body.MessageBody"
#          MessageAttributes: "$request.body.MessageAttributes"
#          MessageSystemAttributes: "$request.body.MessageSystemAttributes"
#          QueueUrl: "{{JiraQueueUrl}}"
#        payloadFormatVersion: "1.0"
#        type: "aws_proxy"
#        connectionType: "INTERNET"
#        integrationHttpMethod: "POST"
x-amazon-apigateway-importexport-version: "1.0"
