openapi: "3.0.1"
info:
  title: Github for Jira Gateway
  description: It routes things
  version: "0.0.1"

paths:
  /$default:
    x-amazon-apigateway-any-method:
      isDefaultRoute: true
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "{{ServerUri}}"
        connectionType: "INTERNET"

  /github/webhooks:
    post:
      responses:
        '200':
          description: "Default response for POST /github/webhooks"
      x-amazon-apigateway-integration:
        integrationSubtype: "SQS-SendMessage"
        credentials: "{{RoleARN}}"
        requestParameters:
          MessageBody: "$request.body.MessageBody"
          MessageAttributes: "$request.body.MessageAttributes"
          MessageSystemAttributes: "$request.body.MessageSystemAttributes"
          QueueUrl: "{{GithubQueueUrl}}"
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"
#        httpMethod: "POST"

  /jira/events:
    post:
      responses:
        '200':
          description: "Default response for POST /github/webhooks"
      x-amazon-apigateway-integration:
        integrationSubtype: "SQS-SendMessage"
        credentials: "{{RoleARN}}"
        requestParameters:
          MessageBody: "$request.body.MessageBody"
          MessageAttributes: "$request.body.MessageAttributes"
          MessageSystemAttributes: "$request.body.MessageSystemAttributes"
          QueueUrl: "{{JiraQueueUrl}}"
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"
#        httpMethod: "POST"
x-amazon-apigateway-importexport-version: "1.0"
