openapi: "3.0.1"
info:
  title: Github for Jira Gateway
  description: It routes things
  version: "0.0.1"

paths:
  /{proxy+}:
    parameters:
      - name: "proxy+"
        in: "path"
        description: "Generated path parameter for proxy+"
        required: true
        schema:
          type: "string"
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        requestParameters:
          integration.request.header.Host: "'{{ServerHost}}'"
          integration.request.path.proxy: "method.request.path.proxy"
        uri: "https://{{ServerHost}}/{proxy}"
        connectionType: "INTERNET"

  /github/webhooks:
    post:
      responses:
        200:
          description: "Default response for POST /github/webhooks"
      x-amazon-apigateway-integration:
        credentials: "{{RoleARN}}"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:{{GithubQueueRegion}}:sqs:path/{{AccountNumber}}/{{GithubQueueName}}/?Action=SendMessage"
        requestParameters:
          MessageBody: "$request.body"
          QueueUrl: "{{GithubQueueUrl}}"
        passthroughBehavior: "when_no_match"
        type: "aws"

  /jira/events:
    post:
      responses:
        200:
          description: "Default response for POST /jira/webhooks"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        credentials: "{{RoleARN}}"
        uri: "arn:aws:apigateway:{{JiraQueueRegion}}:sqs:path/{{AccountNumber}}/{{JiraQueueName}}/?Action=SendMessage"
        requestParameters:
          MessageBody: "$request.body"
          QueueUrl: "{{JiraQueueUrl}}"
        passthroughBehavior: "when_no_match"
        type: "aws"
