version: '3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ngrok http -log stdout --authtoken $NGROK_AUTHTOKEN g4j-proxy:3128

  # creates a proxy to redirect to proper path for localstack
  proxy:
    container_name: g4j-proxy
    image: nginx:alpine
    ports:
      - "3128:3128"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  localstack:
    container_name: g4j-localstack
    image: localstack/localstack:1.4
    environment:
      - DEFAULT_REGION=us-west-1
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=local # runs lambda inside temp directory instead of new docker container
      - SQS_ENDPOINT_STRATEGY=off # sets the SQS queue domain/path to the legacy version
      - LS_LOG=warn # log level
    ports:
      - "4566:4566"
    volumes:
      - ./.localstack:/etc/localstack/init/ready.d
      - ./api-gateway.yml:/api-gateway.yml

  cryptor:
    build: etc/cryptor-mock
    environment:
      CRYPTOR_SIDECAR_CLIENT_IDENTIFICATION_CHALLENGE: "random-string" #has to match the one in env.test
    ports:
      - "26272:26272"

  app:
    container_name: github-for-jira
    depends_on:
      - redis
      - postgres
      - localstack
      - proxy
      - cryptor
    volumes:
      - .:/app
    build:
      context: .
    ports:
      - "8080:8080" # main port
      - "9229:9229" # main debug port
      - "8081:8081" # worker port
      - "9230:9230" # worker debug port
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/jira-dev
      CRYPTOR_URL: http://cryptor:26272
      SQS_BACKFILL_QUEUE_URL: http://localstack:4566/000000000000/backfill
      SQS_PUSH_QUEUE_URL: http://localstack:4566/000000000000/push
      SQS_DEPLOYMENT_QUEUE_URL: http://localstack:4566/000000000000/deployment
      SQS_BRANCH_QUEUE_URL: http://localstack:4566/000000000000/branch
      SQS_TEST_QUEUE_URL: http://localstack:4566/000000000000/test-sqs-client
      SQS_WEBHOOKS_QUEUE_URL: http://localstack:4566/000000000000/webhooks
      REDISX_CACHE_HOST: redis
      NODE_ENV: $NODE_ENV
