services:

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
