version: '3'

services:

  redis:
    image: redis:alpine
    container_name: redis
    network_mode: host

  postgres:
    image: postgres
    container_name: postgres
    network_mode: host
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    network_mode: host
    command: ngrok http 8080

  app:
    depends_on:
      - redis
      - postgres
      - ngrok
    network_mode: host
    volumes:
      - .:/app
    build:
      context: .
