version: '3'

services:

  redis:
    image: redis:alpine
    network_mode: host
#    ports:
#      - 6379

  postgres:
    image: postgres
    container_name: postgres
    network_mode: host
#    ports:
#      - 5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    network_mode: host
    command: ngrok http 4002

  app:
    depends_on:
      - redis
      - postgres
      - ngrok
    network_mode: host
    volumes:
      - .:/app
    build:
      context: .

#    ports:
#      - 4002
