name: Deploy

on: [ push ]

#on:
#  workflow_run:
#    workflows: [ "Test","Build" ] # Dependent workflow
#    types: [ completed ] # Only after dependent workflow is done
#    branches: [ master ] # Only do it on master branch

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest

    # Should only deploy if the dependent workflow is successful
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v1
      - name: Set login details for Heroku
        env:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        run: |
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login $heroku_email
              password $heroku_api_key
          EOF
      - name: Deploy to Heroku.
        env:
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        run: |
          heroku container:login
          heroku container:push --app=$heroku_app_name web worker --recursive
          heroku container:release --app=$heroku_app_name web worker
