name: Deploy

on:
  workflow_run:
    workflows: [ Test, Build ] # Dependent workflow
    types: [ completed ] # Only after dependent workflow is done
    branches: [ main ] # Only do it on main branch

jobs:
  build:
    runs-on: ubuntu-latest

    # Should only deploy if the dependent workflows is successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Deploy to Micros
      env:
        BITBUCKET_API_USER: ${{ secrets.BITBUCKET_API_USER }}
        BITBUCKET_API_PASSWORD: ${{ secrets.BITBUCKET_API_PASSWORD }}
      run: |
        curl --user ${BITBUCKET_API_USER}:${BITBUCKET_API_PASSWORD} \
          --request POST \
          --url https://api.bitbucket.org/2.0/repositories/atlassian/github-for-jira-deployment/pipelines/ \
          --header 'Content-Type: application/json' \
          --data "{
        	\"target\": {
        		\"type\": \"pipeline_ref_target\",
        		\"ref_type\": \"branch\",
        		\"ref_name\": \"master\",
        		\"selector\": {
        			\"type\": \"custom\",
        			\"pattern\": \"deploy\"
        		}
        	},
        	\"variables\": [
        		{
        			\"key\": \"COMMIT_SHA\",
        			\"value\": \"${GITHUB_SHA}\"
        		}
        	]
        }"
