on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'ddev'
    steps:
    - name: 'Deploy'
      id: deploy-to-webapp
      run: echo "Deploy to ddev success"

