name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      env:
        NODE_ENV: test
      with:
        version: 10.x
    - name: npm install, build, and test
      run: |
        npm i -g sequelize
        sequelize db:create --env test
        sequelize db:migrate --env test
        npm install
        npm test
    services:
      postgresql:
        image: postgres
        ports:
        - 5432/tcp
      redis:
        image: redis
        ports:
        - 6379/tcp
