name: Push

on:
  push:
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run build:release

  unit-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: docker-compose up -d app
      - name: wait for app to be ready
        run: curl --version && curl --head -X GET --retry 90 --retry-all-errors --retry-delay 1 http://localhost:8080/version
      - run: yarn run db:test
      - name: Run tests
        env:
          REDISX_CACHE_HOST: localhost
          REDISX_CACHE_PORT: ${{ job.services.redis.ports[6379] }}
          DATABASE_URL: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/jira-test
          AWS_DEFAULT_REGION: us-west-1
          AWS_ACCESS_KEY_ID: localkey
          AWS_SECRET_ACCESS_KEY: localsecret
          AWS_EC2_METADATA_DISABLED: true
        run: yarn test
      - run: docker-compose down

  e2e-test:
    runs-on: ubuntu-22.04

    env:
      NODE_ENV: e2e
      APP_NAME: jira-e2e
      APP_ID: ${{ secrets.E2E_GITHUB_APP_ID }}
      WEBHOOK_SECRET: ${{ secrets.E2E_GITHUB_WEBHOOK_SECRET }}
      GITHUB_CLIENT_ID: ${{ secrets.E2E_GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.E2E_GITHUB_CLIENT_SECRET }}
      PRIVATE_KEY: ${{ secrets.E2E_GITHUB_PRIVATE_KEY }}
      ATLASSIAN_URL: ${{ secrets.E2E_ATLASSIAN_URL }}
      JIRA_ADMIN_USERNAME: ${{ secrets.E2E_JIRA_USERNAME }}
      JIRA_ADMIN_PASSWORD: ${{ secrets.E2E_JIRA_PASSWORD }}
      GITHUB_USERNAME: ${{ secrets.E2E_GITHUB_USERNAME }}
      GITHUB_PASSWORD: ${{ secrets.E2E_GITHUB_PASSWORD }}
      GITHUB_URL: https://github.com

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - name: create .env file
        run: |
          echo "APP_URL=http://localhost" > .env
          echo "WEBHOOK_PROXY_URL=http://localhost" >> .env
          echo "NGROK_AUTHTOKEN=${{ secrets.E2E_NGROK_AUTHTOKEN }}" >> .env
          echo "INSTANCE_NAME=fusion-arc-e2e" >> .env
      - run: docker-compose up -d
      - name: wait for app to be ready
        run: curl --version && curl --head -X GET --retry 90 --retry-all-errors --retry-delay 1 http://localhost:8080/version
      - run: yarn run test:e2e
      - run: docker-compose down

  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          file: Dockerfile
